# Generated by Django 5.1 on 2025-11-26 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guest_remove_test_address_delete_address_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('select', models.CharField(choices=[('mukel', 'Mukel'), ('aavel', 'Aavel')], max_length=10)),
                ('event', models.CharField(choices=[('chandlo', 'Chandlo'), ('marriage', 'Marriage')], max_length=10)),
                ('bride_groom', models.CharField(blank=True, max_length=100, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_guestRecord_FK', to='api.guest')),
            ],
        ),
    ]
