# Generated by Django 5.1 on 2026-01-09 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guestrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrecord',
            name='event_type',
            field=models.CharField(choices=[('chandlo', 'Chandlo'), ('marriage', 'Marriage')], default='chandlo', max_length=10),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('chandlo', 'Chandlo'), ('marriage', 'Marriage')], max_length=10)),
                ('select_type', models.CharField(choices=[('mukel', 'Mukel'), ('aavel', 'Aavel')], max_length=10)),
                ('bride_groom_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('date', 'event_type', 'select_type', 'bride_groom_name')},
            },
        ),
        migrations.AlterField(
            model_name='guestrecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_guestRecord_FK', to='api.event'),
        ),
    ]
