# Generated by Django 5.1 on 2026-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_guestrecord_event_type_event_alter_guestrecord_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date')},
        ),
    ]
