# Generated by Django 5.1 on 2026-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrecord',
            name='pay_later',
            field=models.BooleanField(default=False),
        ),
    ]
