# Generated by Django 5.1 on 2026-01-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_user_guest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
    ]
