# Generated by Django 5.1 on 2026-02-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
